version: "3.4"
services:
  redis-master1:
    container_name: rs-master1
    hostname: rs-master1
    image: redis:5.0.5
    restart: always
    ports:
      - 7001:7001
    volumes:
      - ./redis/redis-master1.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data/master1:/data

  redis-slave1:
    container_name: rs-slave1
    hostname: rs-slave1
    image: redis:5.0.5
    restart: always
    ports:
      - 7002:7002
    volumes:
      - ./redis/redis-slave1.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data/slave1:/data