global:
  # 163服务器
  smtp_smarthost: 'smtp.163.com:25'
  # 发邮件的邮箱
  smtp_from: 'java_zlm@163.com'
  # 发邮件的邮箱用户名
  smtp_auth_username: 'java_zlm@163.com'
  # 发邮件的邮箱密码
  smtp_auth_password: 'TPP***'　　
  # TLS验证　
  smtp_require_tls: false

route:
  group_by: [ 'alertname' ]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10m
  receiver: live-monitoring

receivers:
  - name: 'live-monitoring'
    email_configs:
      # 收邮件的邮箱
      - to: 'lmay@lmaye.com'