version: "3"
services:
  rabbitmq:
    container_name: lmay-rabbitmq
    image: rabbitmq:latest
    build: .
    restart: on-failure
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq