# 镜像
FROM rabbitmq:latest
# 作者
MAINTAINER lmay Zhou <lmay@lmaye.com>
# 启动插件
RUN rabbitmq-plugins enable --offline rabbitmq_management rabbitmq_mqtt rabbitmq_federation rabbitmq_federation_management rabbitmq_stomp