version: "3"
services:
  rabbitmq:
    container_name: lmay-rabbitmq
    image: rabbitmq:3.8.16-management
    restart: on-failure
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    volumes:
      - ./data:/var/lib/rabbitmq