version: "3"
services:
  fastdfs-tracker:
    # 容器名称
    container_name: fastdfs-tracker
    # 镜像:版本
    image: season/fastdfs:1.2
    # 必须是host, 原因是当上传文件时，tracker会把storage的IP和端口发给client，如果是bridge模式，则发送的是内网IP，client无法访问到。
    network_mode: host
    # 重启机制
    # -- no: 禁止自动重启容器(默认);
    # -- always: 无论如何容器都会重启;
    # -- on-failure: 当出现on-failure报错时, 容器重新启动;
    restart: on-failure
    command: tracker
    # 端口
#    ports:
#      - 22122:22122
    # 持久化挂载
    volumes:
      - ./tracker/data:/fastdfs/tracker/data

  fastdfs-storage:
    container_name: fastdfs-storage
    image: season/fastdfs:1.2
    network_mode: host
    restart: on-failure
    command: storage
#    ports:
#      - 23000:23000
    environment:
      - TRACKER_SERVER=192.168.0.10:22122
    volumes:
      - ./storage/data:/fastdfs/storage/data
      - ./storage/path:/fastdfs/store_path
    depends_on:
      - fastdfs-tracker

  fastdfs-nginx:
    container_name: fastdfs-nginx
    image: season/fastdfs:1.2
    network_mode: host
    restart: on-failure
    command: nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf/nginx.conf
      - ./storage/path:/fastdfs/store_path
    environment:
      - TRACKER_SERVER=192.168.0.10:22122
