version: "3"
services:
  mysql:
    container_name: lmay-mysql
    image: mysql:8.0.16
    environment:
      MYSQL_DATABASE: nacos_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Shanghai
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql/my.cnf:/etc/my.cnf
      - ./mysql/data:/var/lib/mysql
      # 数据库初始化脚本
      - ./mysql/init:/docker-entrypoint-initdb.d/

  nacos:
    container_name: lmay-nacos
    image: nacos/nacos-server:latest
    restart: on-failure
    ports:
      - 8848:8848
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_MASTER_SERVICE_HOST=lmay-mysql
      - MYSQL_MASTER_SERVICE_DB_NAME=nacos_db
      - MYSQL_MASTER_SERVICE_PORT=3306
      - MYSQL_SLAVE_SERVICE_HOST=lmay-mysql
      - MYSQL_SLAVE_SERVICE_PORT=3306
      - MYSQL_MASTER_SERVICE_USER=root
      - MYSQL_MASTER_SERVICE_PASSWORD=root
    volumes:
      - ./nacos/custom.properties:/home/nacos/init.d/custom.properties
      - ./nacos/logs/:/home/nacos/logs
    depends_on:
      - mysql