version: "3.4"
services:
  redis-7005:
    container_name: redis-7005
    image: redis:5.0.5
    restart: always
    ports:
      - 7005:7005
#      - 17005:17005
    volumes:
      - ./redis/redis-7005.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data/7005:/data
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-7006:
    container_name: redis-7006
    image: redis:5.0.5
    restart: always
    ports:
      - 7006:7006
#      - 17006:17006
    volumes:
      - ./redis/redis-7006.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data/7006:/data
    command: redis-server /usr/local/etc/redis/redis.conf