version: "3.4"
services:
  redis-7003:
    container_name: redis-7003
    image: redis:5.0.5
    restart: always
    ports:
      - 7003:7003
#      - 17003:17003
    volumes:
      - ./redis/redis-7003.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data/7003:/data
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-7004:
    container_name: redis-7004
    image: redis:5.0.5
    restart: always
    ports:
      - 7004:7004
#      - 17004:17004
    volumes:
      - ./redis/redis-7004.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data/7004:/data
    command: redis-server /usr/local/etc/redis/redis.conf