version: "3"
services:
  openresty:
    # 容器名称
    container_name: lmay-openresty
    # 镜像:版本
    image: openresty/openresty:alpine
    # 重启机制
    # -- no: 禁止自动重启容器(默认);
    # -- always: 无论如何容器都会重启;
    # -- on-failure: 当出现on-failure报错时, 容器重新启动;
    restart: on-failure
    # 端口
    ports:
      - 80:80
    # 持久化挂载
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./html:/usr/local/openresty/nginx/html
